name: hybris-mobian rootfs-builder

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: true
      matrix:
        arch: [arm64, armhf, amd64]
        template: [rootfs-builder]
        dist: [bullseye]
        namespace: [hybrismobian]

    name: ${{ matrix.template }}:${{ matrix.dist }} on ${{ matrix.arch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: QEMU set-up
        uses: docker/setup-qemu-action@v1

      - name: Create build dir
        run: mkdir -p /tmp/buildd-results

      - name: Pull container
        run: docker pull quay.io/${{ matrix.namespace }}/${{ matrix.template }}:${{ matrix.dist }}-${{ matrix.arch }}

      - name: Start Container
        run: echo CONTAINER_HASH=$(docker run --detach --privileged -v /tmp/buildd-results:/buildd -v /sys/fs/cgroup:/sys/fs/cgroup -v ${PWD}:/buildd/sources  --security-opt seccomp:unconfined quay.io/${{ matrix.namespace }}/${{ matrix.template }}:${{ matrix.dist }}-${{ matrix.arch }} /sbin/init) >> $GITHUB_ENV

      - name: Build rootfs
        run: docker exec $CONTAINER_HASH /bin/sh -c 'cd /buildd/sources; debos --disable-fakemachine -t architecture:${{ matrix.arch }} device.yml'

      - name: Upload Release Asset
        id: upload-release-asset
        if: "${{ github.ref == 'refs/heads/feature/master' }}"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./hybrismobian-rootfs-api28gsi-${{ matrix.arch }}.tar.gz
          asset_name: hybrismobian-rootfs-api28gsi-${{ matrix.arch }}.tar.gz
          asset_content_type: application/gzip
